build: fix typo in buildversion.py
Fixes the following build error:

  Building ld scripts
Traceback (most recent call last):
  File "./scripts/buildversion.py", line 134, in <module>
    main()
  File "./scripts/buildversion.py", line 114, in main
    cleanbuild, toolstr = tool_versions(options.tools)
  File "./scripts/buildversion.py", line 90, in tool_versions
    vers[isbinutils] = "mixed"
NameError: global name 'vers' is not defined
Makefile:160: recipe for target 'out/romlayout16.lds' failed

Signed-off-by: Roger Pau Monné <roger.pau@citrix.com>
(cherry picked from commit 3b8c5378dfe24ca8dfeabbcc435c7eb9e2d8d769)